### PR TITLE
Defenseexplanation

### PR DESCRIPTION
**Pull request by tobyfey**

### CODE REVIEW

**Review by miabonardi — CHANGES_REQUESTED** [review]
Looks great. 

Suggested change is that we should have the following logic on any template language to accommodate tenant vs attorney/someone else references

% if person_answering == "tenant":
Language to refer to tenant: "You", "Your" etc
% else:
Language to refer to tenant: "the tenant" etc
% endif

**Comment by tobyfey** [comment]
Also, I was going to use the same template in a document to download.  That seems like the second person is much better to use in the document, right?

**Comment by miabonardi** [comment]
> I think for stuff that is explanations, not questions, using the second person makes more sense and is easier to understand. Like how the second person is used in terms now - that seems easier to understand than when it referred to tenant before.
> 
> If we do make the change, one thing that pops up in this part as well as a few other places - when the interview is referring to the person entering information into the interview, I feel like "you" makes more sense regardless if it is the tenant or somebody else.

Our current process is to do it throughout and being inconsistent is likely most confusing. Regarding terms, [this issue](https://github.com/LemmaLegalConsulting/docassemble-MOHUDEvictionProject/issues/374) is still open and will be addressed once anyone can advise how to add the conditional logic to the terms. The terms currently use both first and second person where it makes sense in the definition. The same formatting does not work there. However, in these templates that formatting will work and I think it should be added for consistency. @nonprofittechy please advise if otherwise

**Comment by miabonardi** [comment]
> Also, I was going to use the same template in a document to download. That seems like the second person is much better to use in the document, right?

Which template are you referring to? Second person makes sense if it is a "next steps" document, but anything filed in court should use defendant / tenant's name / the tenant

**Comment by tobyfey** [comment]
I meant the same template block used in the defense to add to a downloadable document.  I thought I added that in the first paragraph of the defense explanation.  I need to update the headings of the unlawful detainer defenses in the defense explanation to match the changes I made in the answer document.

**Pull request closed without merging**
