### PR TITLE
Review block updates

### PR DESCRIPTION
**Pull request by miabonardi**

### CODE REVIEW

**Comment by miabonardi** [comment]
@tobyfey

1. This looks REALLY good. I think this feature will be great to add and build upon and makes it more clear what is included in the answer and what is not. 
2. However, when answers are edited and changed, the icons and new cool guiding words do not update. For this reason, I think we need to update this before merging. 

This is not a priority this month though and should be deprioritized.

**Comment by tobyfey** [comment]
@miabonardi the icons do update generally, although I may have missed some defenses to update.

**Comment by miabonardi** [comment]
They didn't update for me when I tested. Specifically the UD defenses when 
1) under UD, I switched from having a lease to not having one and it didn't update 
2) I switched from UD to only R&P eviction type and all the UD stuff still showed

**Comment by tobyfey** [comment]
Yes, I didn't have all of the necessary defenses listed in recompute in all of the places that allow you to edit the lease.  Plus the one place that did recompute the ud defense, the recompute for defense_logic was before the individual defense.  That would have been the lease question right under the ud defense.  Do you remember if you edited whether there was a lease there or above?

The second issue, switching from UD to R and P, is a bigger issue.  The logic for the defenses doesn't include a distinction between UD and R and P.  That's controlled in the interview order, so it doesn't to recompute the defense after changing that.  I think we need to change the logic for the defenses.

**Comment by miabonardi** [comment]
- Remove not included / `show if: False`
- Remove "The defenses listed can apply in all evictions."
- Claims and defenses first
- Accordion review screen - two levels may be possible. Try reviewing other UI for this
- Remove colon "How many units are in the building or apartment complex?:"
- Rephrase "[answered above]" to "[edit above]"
- Multiple edit buttons ok, but add caution that affects multiple docs

**Review by miabonardi — COMMENTED** [review]
- [x] User's attorney does not appear on review screen - https://github.com/LemmaLegalConsulting/docassemble-MOHUDEvictionProject/issues/364
- [ ] Review does not show if more than one Plaintiff entered
- [ ]  Review does not show Plaintiff's attorney 
Screen Shot 2023-12-05 at 6 45 50 PM
Resolved

**Comment by miabonardi** [comment]
> * User's attorney does not appear on review screen - [Add user's attorney to review screen #364](https://github.com/LemmaLegalConsulting/docassemble-MOHUDEvictionProject/issues/364)
> * Review does not show if more than one Plaintiff entered
> * Review does not show Plaintiff's attorney
> 
> Screen Shot 2023-12-05 at 6 45 50 PM

Disregard while I continue testing

**Comment by miabonardi** [comment]
Screen Shot 2023-12-05 at 7 06 49 PM

**Comment by miabonardi** [comment]
> Screen Shot 2023-12-05 at 7 15 31 PM
> @tobyfey This one is confusing to me because all the other checkboxes just say "included in answer" but this one is explaining something else. Is there another way we can show this?

@tobyfey I just finished up my review and did a commit [c607a04](https://github.com/LemmaLegalConsulting/docassemble-MOHUDEvictionProject/pull/424/commits/c607a04c330dd422479de1b0e5eca5d7adf45bd3). I think adjusting the checkbox for notice (when all others say "included in answer") is the only thing preventing me from merging. Up to @nonprofittechy

**Comment by tobyfey** [comment]
@miabonardi What if it looks like this
image

**Comment by tobyfey** [comment]
That defense has sub-defenses, and there could be more than one, so I think it is important to explain that.

**Pull request merged**
