### PR TITLE
Plain language review of current terms

### LINKED ISSUE #375: PL review of terms

### PR DESCRIPTION
**Pull request by miabonardi**
- Fix #375 
- Update #374 (no attorney logic yet)
- Will complete #344 in a different PR

### CODE REVIEW

**Comment by tobyfey** [comment]
I think this definition about action is confusing in regards to get help, because i don't think it's natural to think of a court helping somebody, and would be less confusing with an example

A lawsuit with the purpose to get help from a judge/court, such as when a landlord asks a court to evict a tenant or when a landlord or tenant asks the court to order the other party to pay money.. 

Affirmative Defense - I think the important part about affirmative defense is the distinction between affirmative defenses are different than saying that allegation by the landlord is wrong.  I don't know if the glossary is the place to make that clear though.

Allegation - i don't like using claim because of its potential meaning as a cause of action - i'd stick with assertion

Appearance - I feel like "coming into court" in the original definition is confusing, but in Ohio, somebody can make an appearance by filing something, so I don't think the new definition would work if Missouri is like Ohio.

**Comment by tobyfey** [comment]
Those comments above are based on the first commit, so they may be inappropriate

**Comment by tobyfey** [comment]
Dismissal with/without Prejudice - I think Ending is better than Closing

Statute - I think it is worth keeping in the information about the Revised Statutes of Missouri.

**Comment by miabonardi** [comment]
> Those comments above are based on the first commit, so they may be inappropriate

If you click on "Files changed" you can see all changes this PR would make to main on merge and read the definitions more clearly. It combines all commits

**Pull request merged**
