### PR TITLE
consolidate buttons on review screen

### PR DESCRIPTION
**Pull request by tobyfey**
### Updating review screen

[<Insert links>](https://github.com/LemmaLegalConsulting/docassemble-MOHUDEvictionProject/pull/488)

### In this PR, I have:

* [x] Manually tested to ensure my PR is working
* [x] Ensured issues that this PR closes will be [automatically closed](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
* [x] Requested review from Mia or Quinten

### CODE REVIEW

**Review by miabonardi — CHANGES_REQUESTED** [review]
As discussed in Slack -- we shouldn't put the conditional logic inside ${ } because it will be harder to translate

Additionally, I dont think this is what @nonprofittechy was asking for. Quinten, can you explain how to loop through the screens and have one button for groups of things to edit? This makes it look like only some things can be edited. 

Screen Shot 2024-01-08 at 11 41 34 AM

**Comment by tobyfey** [comment]
I didn't add any conditional logic inside ${ }, I added backslashes at the end of the text to fix the problem.

**Comment by miabonardi** [comment]
Ok! That helps then. I still dont think this is exactly what @nonprofittechy was asking.

**Comment by miabonardi** [comment]
From @tobyfey

> I saw in Pfeiffer a review block that seems to be like Quinten is talking about. I don't know if that will work with the factors that are asked in different spots (which we were using edit above before).

Toby-- what do you mean by "the factors that are asked in different spots"?

**Comment by miabonardi** [comment]
- [ ] Get rid of horizontal lines
- [ ] Use plain language headings for defense language
- [ ] An icon makes sense to use, but explain what it means (maybe choose a different heading), fa icon feature?
- [ ] Use consistent headings (Defense:, Defense:, etc), step down in size
- [ ] Consider adding collapsable review/edit screens

**Comment by nonprofittechy** [comment]
Maybe a clearer information hierarchy that uses heading level 2, 3, and 4 with a little longer text like this:

image

**Comment by miabonardi** [comment]
I tested this on mobile. While we wait on accordion-type edit screens, what are your thoughts on putting an additional "Continue" type button at the top of the review page screen (in addition to having one at the bottom)?

**Review by miabonardi — CHANGES_REQUESTED** [review]
### This looks fantastic! There is a lot of really great work here. The accordion is a huge improvement! 

### A few things I noticed: 

1. The screen defaults to opening on "Potential Eviction Defenses". I think it makes more sense to default to open on "Information about you" so the user can review each folder in order.

Currently default opens here:

Screen Shot 2024-02-21 at 7 35 10 AM

And I think it should default open here:

Screen Shot 2024-02-21 at 7 35 37 AM

2. There is something buggy going on with the footer. I was in a Chrome browser on Mac and captured it in two screenshots, but note I scrolled to the side to grab it. It is only on the review screen / screen with accordion that this happens. 

Screen Shot 2024-02-21 at 7 36 42 AM
Screen Shot 2024-02-21 at 7 36 59 AM

3. Under "About your rental agreement" an Edit button appeared twice and I marked up the following changes. I'll note here and below again: **I think we should remove colons after question marks and make all of the user's answers on review bold.**

Screen Shot 2024-02-21 at 7 38 07 AM

4. Nothing showed up under this defense. I answered no to `tenant_has_disability`. 

Screen Shot 2024-02-21 at 7 40 35 AM

5. Noting here again this as an example of where we should remove colons after question marks and make all of the user's answers on review bold.

Screen Shot 2024-02-21 at 7 41 45 AM

7. I think we should remove `id: defenses explanation` from being shown on the review screen loop. I think it's too repetitive to show this to the user every time they edit an answer. I think it should also not be shown where it is right now. Now that Discovery and other motions are added, I think having this come after discovery choice (at which point we will know whether a motion to shorten time will be added) would be a good place for this final review screen to be. 

Screen Shot 2024-02-21 at 7 54 48 AM

### _This will also need mobile testing_

**Comment by miabonardi** [comment]
See #376

**Comment by miabonardi** [comment]
Updated and ready for a new review, Mia and Toby testing on mobile, Toby testing again for 4. 

@nonprofittechy can you check this out: 

 2. There is something buggy going on with the footer. I was in a Chrome browser on Mac and captured it in two screenshots, but note I scrolled to the side to grab it. It is only on the review screen / screen with accordion that this happens. 

Screen Shot 2024-02-21 at 7 36 42 AM
Screen Shot 2024-02-21 at 7 36 59 AM

**Comment by tobyfey** [comment]
I don't see the footer issue on Android.

**Comment by tobyfey** [comment]
I can't figure out how to recreate the problem with the footer.

**Comment by tobyfey** [comment]
I tried Chrome and Firefox and the responsive design mode on each.

**Pull request merged**
