### PR TITLE
fix spacing css on preview page  #459

### PR DESCRIPTION
**Pull request by hamzzy**
#459

### CODE REVIEW

**Comment by miabonardi** [comment]
@nonprofittechy is this what you wanted? I'm not really sure what it was. 

Screen Shot 2023-12-20 at 11 08 32 AM

**Review by nonprofittechy — CHANGES_REQUESTED** [review]
@hamzzy this doesn't feel like enough white space to me, although it appears you added the top margin to the H3--double check that's the right element I guess, and experiment with a little more space?

My goal was to get a top margin on the `note` field so there's more separation between each section of the review page. It should be about a full `em`. Also let's use `em` or a similar responsive separator and make sure it still looks good in mobile view.

image

**Comment by nonprofittechy** [comment]
Looking at this, I think we should also consider if we can reduce the number of separate `button` expressions on this page so there's one `edit` button per page that it takes you to. if that's already the case, not much we can change, but it's a little busy. The whitespace between sections will help, but maybe there's more we can do.

**Comment by miabonardi** [comment]
> Looking at this, I think we should also consider if we can reduce the number of separate `button` expressions on this page so there's one `edit` button per page that it takes you to. if that's already the case, not much we can change, but it's a little busy. The whitespace between sections will help, but maybe there's more we can do.

@tobyfey Can you take a look at reducing the number of buttons on the review screen? I think this is a separate issue that we can address in a different PR.

**Comment by hamzzy** [comment]
> @hamzzy this doesn't feel like enough white space to me, although it appears you added the top margin to the H3--double check that's the right element I guess, and experiment with a little more space?
> 
> My goal was to get a top margin on the `note` field so there's more separation between each section of the review page. It should be about a full line. Also let's use `em` or a similar responsive separator and make sure it still looks good in mobile view.
> 
> image
> 
> edit: looking again, maybe the two margins are reversed. we want more top margin so each section is clearly separate and less bottom margin. but use a responsive measurement.

i will check it out and re fix

**Review by miabonardi — COMMENTED** [review]
I still dont think this is there yet. Up to @nonprofittechy 

Desktop:

Screen Shot 2024-01-24 at 7 49 36 AM

Screen Shot 2024-01-24 at 7 50 08 AM

Mobile:

Screenshot 2024-01-24 at 7 57 22 AM

**Comment by miabonardi** [comment]
@hamzzy Could you try to fix the spacing here again?

**Comment by miabonardi** [comment]
@hamzzy checking in on this

**Comment by miabonardi** [comment]
@nonprofittechy are we still proceeding with this change, or does #492 supersede?

**Comment by nonprofittechy** [comment]
Food question. The idea was just a bit more clear separation between the different sections. If the new PR gives that, this might be moot

**Comment by miabonardi** [comment]
@tobyfey what do you think

**Comment by nonprofittechy** [comment]
Going to close this for now. I do still think extra padding between the review screen H2 elements is a good idea in general, but I think it should be revisited in light of the new accordion sections and might need more adjustment.

**Pull request closed without merging**
